version: '3.7'

services:
  ts-node-docker:
    build:
      context: .
      dockerfile: Dockerfile
      target: base
    environment:
      - MONGO_URI
      - PORT
      - JWT_SECRET
    volumes:
      - ./src:/user/src
      - ./nodemon.json:/user/nodemon.json
    container_name: ts-node-docker
    expose:
      - '3050'
    ports:
      - '3050:3050'
    command: npm run start